# Generated by Django 2.2 on 2019-09-14 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=200, verbose_name='Blog Title')),
                ('Author', models.CharField(max_length=200, verbose_name='Author')),
                ('Genre', models.IntegerField(choices=[(1, 'Reviews'), (2, 'Profiles'), (3, 'Rant'), (4, 'Inspirational')], verbose_name='Genre')),
                ('Content', models.CharField(max_length=2000, verbose_name='Content')),
            ],
        ),
    ]
